### ISSUE TITLE
抓取到网页内容后，保存数据库失效，可看到insert语句打印，但是最终无法保存至数据库

### ISSUE THREAD

**Issue by zhangyyii** [chocotan/nekocat#2]
![image](https://user-images.githubusercontent.com/30514963/51082743-599c2400-1748-11e9-85ae-cb5216e7cf22.png)
![image](https://user-images.githubusercontent.com/30514963/51082744-60c33200-1748-11e9-9ca1-14fbf69d34c0.png)

**Comment by chocotan** [comment]
目前设计如此
可以加一个LoggingInterceptor来记录每次抓取和处理的日志

下个版本会默认把异常日志打印出来
